### ISSUE TITLE
When inserting images does not call textViewDidChange.

### ISSUE THREAD

**Issue by hstdt** [Deadpikle/iOS-Rich-Text-Editor#5]
As title says, whenever textView changed, such as typing or setting bulleted list will call delegate `textViewDidChange` except for inserting images.

**Comment by hstdt** [comment]
Here's my code trying to solve this problem.

https://github.com/Deadpikle/iOS-Rich-Text-Editor/pull/6

**Comment by Deadpikle** [comment]
Closed by #7
